[advisories]
version = 2
yanked = "deny"
ignore = [
    # This is temporary. See avbroot's deny.toml.
    "RUSTSEC-2023-0071",
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "GPL-3.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "warn"
deny = [
    # https://github.com/serde-rs/serde/issues/2538
    { name = "serde_derive", version = ">=1.0.172,<1.0.184" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/chenxiaolong/avbroot",
    "https://github.com/chenxiaolong/bzip2-rs",
    "https://github.com/chenxiaolong/zip",
]
